from datetime import datetime

DATE = f"{datetime.now().year}-0{datetime.now().month}"

JC_TAG = '#9JUVCV0L'
JC_ATTACK_WINS = 70
JC_DONATIONS = 5000
JC_CLAN_GAME_POINTS = 1000

EL_TAG = '#PQP2Y2QV'
EL_ATTACK_WINS = 70
EL_DONATIONS = 5000
EL_CLAN_GAME_POINTS = 1000

PB_TAG = '#PCCJUVJQ'
PB_ATTACK_WINS = 60
PB_DONATIONS = 5000
PB_CLAN_GAME_POINTS = 1000

HB_TAG = '#RCPLRRJ8'
HB_ATTACK_WINS = 70
HB_DONATIONS = 6000
HB_CLAN_GAME_POINTS = 1000

AV_TAG = '#GGUR2Y2'
AV_ATTACK_WINS = 60
AV_DONATIONS = 5000
AV_CLAN_GAME_POINTS = 1000

EG_TAG = '#P9RLJR2J'
EG_ATTACK_WINS = 50
EG_DONATIONS = 3500
EG_CLAN_GAME_POINTS = 1000

SG_TAG = '#29VJYRLY8'
SG_ATTACK_WINS = 20
SG_DONATIONS = 1000
SG_CLAN_GAME_POINTS = 1000


CLAN_TAGS = [JC_TAG, EL_TAG, PB_TAG, HB_TAG, AV_TAG, EG_TAG, SG_TAG]
CLAN_SHORTS = {
    JC_TAG: 'JC',
    EL_TAG: 'EL',
    PB_TAG: 'PB',
    HB_TAG: 'HB',
    AV_TAG: 'AV',
    EG_TAG: 'EG',
    SG_TAG: 'SG',
}

CLAN_REQUIREMENTS = {
    JC_TAG:[JC_ATTACK_WINS, JC_DONATIONS, JC_CLAN_GAME_POINTS],
    EL_TAG:[EL_ATTACK_WINS, EL_DONATIONS, EL_CLAN_GAME_POINTS],
    PB_TAG:[PB_ATTACK_WINS, PB_DONATIONS, PB_CLAN_GAME_POINTS],
    HB_TAG:[HB_ATTACK_WINS, HB_DONATIONS, HB_CLAN_GAME_POINTS],
    AV_TAG:[AV_ATTACK_WINS, AV_DONATIONS, AV_CLAN_GAME_POINTS],
    EG_TAG:[EG_ATTACK_WINS, EG_DONATIONS, EG_CLAN_GAME_POINTS],
    SG_TAG:[SG_ATTACK_WINS, SG_DONATIONS, SG_CLAN_GAME_POINTS],

}

CLAN_NAMES = {
    CLAN_TAGS[0] : "JOHN CENA",
    CLAN_TAGS[1] : "#1 ELITE",
    CLAN_TAGS[2] : "playyboys♥",
    CLAN_TAGS[3] : "HELL BOYS",
    CLAN_TAGS[4] : "AvengerS.",
    CLAN_TAGS[5] : "ELITE GAMERZ",
    CLAN_TAGS[6] : "sports game",
}